version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stackerytest-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7gklwmzkyvy0"
s3_prefix = "stackerytest-test"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
